### 1. เรียกดูรายชื่อบทบาททั้งหมด
GET http://localhost:3000/api/roles
Accept: application/json

### ---------------------------------------

### 2. เพิ่มบทบาทใหม่ (พิมพ์เองเพื่อป้องกัน Error)
POST http://localhost:3000/api/roles
Content-Type: application/json

{
  "name": "Akharacha_Admin"
}

### ---------------------------------------

### 3. แก้ไขข้อมูล (ระบุ ID ที่ต้องการเปลี่ยน)
PUT http://localhost:3000/api/roles/1
Content-Type: application/json

{
  "name": "Admin_Pro"
}

### ---------------------------------------

### 4. ลบข้อมูลออกจากระบบ
DELETE http://localhost:3000/api/roles/3