################################
### ROLES
################################

### CREATE ROLE
POST http://localhost:3000/roles
Content-Type: application/json

{
  "RoleName": "Admin"
}

###

### GET ALL ROLES
GET http://localhost:3000/roles

###

################################
### USERS
################################

### CREATE USER
POST http://localhost:3000/users
Content-Type: application/json

{
  "Username": "opezare",
  "RoleID": 1
}

###

### GET ALL USERS
GET http://localhost:3000/users

###

################################
### HOSPITAL ROOMS
################################

### CREATE ROOM
POST http://localhost:3000/rooms
Content-Type: application/json

{
  "RoomNumber": "101",
  "Type": "ICU",
  "Capacity": 2,
  "Status": "Available"
}

###

### GET ALL ROOMS
GET http://localhost:3000/rooms

###

### GET ROOM BY ID
GET http://localhost:3000/rooms/1

###

### UPDATE ROOM
PUT http://localhost:3000/rooms/1
Content-Type: application/json

{
  "RoomNumber": "101",
  "Type": "ICU",
  "Capacity": 2,
  "Status": "Occupied"
}

###

### DELETE ROOM
DELETE http://localhost:3000/rooms/1
